name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Test
        run: cargo test
      - name: Upload lockfile
        uses: actions/upload-artifact@v4
        with:
          name: cargo-lock
          path: Cargo.lock
